---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: fedora38
    image: docker.io/geerlingguy/docker-fedora38-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
  - name: debian12
    image: docker.io/geerlingguy/docker-debian12-ansible
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
